ratings = [100,150,250]; % Ratings for diesel generators in kW, one for each generator
D = readtimetable(...
    'data/electrical_load_generic_peak-500kW_1yr_dt-1hr.csv'...
    ); %Electrical demand as a timetable
S = readtimetable(...
    'data/normalized_solar_production.csv'...
    ); %Normalized solar array output for a year
r = 250; %Total Solar PV array rating
K = length(ratings); %number of diesel generators
L = 1; %number of timesteps

